version: '{build}'
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
skip_commits:
  files:
  - doc/*
  - readme.md
nuget:
  disable_publish_on_pr: true
os: Visual Studio 2017
configuration: Release
cache:
 - '%APPDATA%\npm-cache -> src\nerdbank-gitversioning.npm\package.json'
init:
- ps: >-
    git config --global user.name appveyor

    git config --global user.email me@appveyor.com
environment:
  VisualStudioVersion: 15.0
install:
- ps: >-
    npm install npm -g
before_build:
- ps: >-
    .\init.ps1

    #$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
- ps: >-
    .\build.ps1
test:
  assemblies:
    only:
    - NerdBank.GitVersioning.Tests.dll
artifacts:
- path: bin\**\*.nupkg
- path: bin\js\*.tgz
