version: 1.0.{build}
skip_tags: true
os: Visual Studio 2017 RC
configuration: Release
cache:
 - '%APPDATA%\npm-cache -> src\nerdbank-gitversioning.npm\package.json'
init:
- ps: >-
    git config --global user.name appveyor

    git config --global user.email me@appveyor.com
environment:
  VisualStudioVersion: 15.0
  NuGetApiKey:
    secure: Ql19CstT9GvFNeSIAjXvgHXZg+/pNaYJ2jVkzde4LT2vwSyjiQgQ+M332wVYtu+r
install:
- ps: >-
    npm install npm -g
before_build:
- ps: >-
    .\init.ps1

    #$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
- ps: >-
    Write-Host "VisualStudioVersion = $env:VisualStudioVersion"

    $env:VisualStudioVersion = '15.0'

    .\build.ps1
artifacts:
- path: bin\**\*.nupkg
- path: bin\js\*.tgz
on_success:
- ps: >-
    if ($env:NuGetApiKey -and $env:APPVEYOR_REPO_TAG_NAME -match "^v\d") {
        Write-Output "Publishing release packages to nuget.org due to pushed tag $env:APPVEYOR_REPO_TAG_NAME"
        Get-ChildItem bin\Release\Nerdbank.GitVersioning.NuGet\*.nupkg -exclude *.symbols.nupkg |% {
            nuget push $_ -ApiKey $env:NuGetApiKey
        }
    }